### ISSUE TITLE
`offset` is missing from `node.source`

### ISSUE THREAD

**Issue by romainmenke** [postcss/sugarss#105]
For example: https://github.com/postcss/sugarss/blob/f880b772ee45d4def8d7b7555272a533e0dfc524/parser.js#L141

While the default PostCSS parser for example has:
https://github.com/postcss/postcss/blob/77420d62919b4d53921a113bbc939ad5e5b49fe6/lib/parser.js#L361

```js
  getPosition(offset) {
    let pos = this.input.fromOffset(offset)
    return {
      column: pos.col,
      line: pos.line,
      offset
    }
  }
```

`offset` was likely added later in PostCSS and wasn't backported to this syntax.

This is not trivial to fix because the tokenizer also doesn't record the offset values in tokens.
I think this issue is fairly minor, but maybe someone is willing to volunteer their time :) (I don't use `sugarss` myself)

**Comment by ai** [comment]
I will also fix `sugarss` by adding `offset`

**Comment by kodsurfer** [comment]
hello, please check PR #107

**Comment by ai** [comment]
Fixed by https://github.com/postcss/sugarss/pull/108
