### ISSUE TITLE
Project logo #2

### ISSUE THREAD

**Issue by cakeinpanic** [postcss/sugarss#18]
Hello!
I've seen[ logo developed by Maria Keller](https://github.com/postcss/sugarss/issues/7), it's cute, but looks unpolished and has too many details.
I've showed it to my friend, illustrator [Leonid Zarubin](http://miaou-miaou.ru/) and he'd drawn his version, which is more laconic and readable.
I like it more and suggest to use it as project logo
What do you think? 
![sugar_2](https://cloud.githubusercontent.com/assets/588916/13874013/35663270-ed06-11e5-9ef6-cb47b508eed9.png)

**Comment by ai** [comment]
Yeap, I agree that current logo drawing not ideal.

But this logo is just a draft. Problems:

1. Hands has different length (especially with perspective)
2. eyes are not in symmetric position.
3. there is no story like in current one.

**Comment by cakeinpanic** [comment]
Very strange list of requirements

**Comment by ai** [comment]
“eyes are not in symmetric position” is not a expected requirement? ;)

**Comment by jt3k** [comment]
eye are not happy

**Comment by cakeinpanic** [comment]
@jt3k new symmetrical happy eyes provided!
![img_18032016_141158](https://cloud.githubusercontent.com/assets/588916/13881269/440758ba-ed31-11e5-9cfe-0358dd29a48d.png)

**Comment by jt3k** [comment]
fixed :D 
![](https://i.imgur.com/05tAw8s.png)
