### ISSUE TITLE
PostCSS Middleware

### ISSUE THREAD

**Issue by admdh** [postcss/sugarss#22]
I would like to use SugarSS with PostCSS Middleware. What is the best way to set it up?
i'm trying to do something like this but it doesn't work
```
server.use('/webroot/*.sss', postcssMiddleware({
	src: function(req) { return path.join(__dirname, req.originalUrl); },
	plugins: postcssPlugins,
	syntax: sugarss
}));
```
or this issue should be directed to PostCSS Middleware plugin?

**Comment by TrySound** [comment]
@admdh Yep. Middleware should allow more options. Thanks for pointing.

**Comment by admdh** [comment]
Thanks for your kind help!
