### ISSUE TITLE
Importing/including plain CSS inline

### ISSUE THREAD

**Issue by DavidOliver** [postcss/sugarss#33]
This is more of a question than an issue - hope that's okay.

I was wondering if/how one can `@import` plain CSS files into a `.sss` file.

My current use case is inserting normalize.css at the beginning (for which I think I could concatenate), but sometimes I'll also want to include a plain CSS file part way through my stylesheet.

Thanks.

**Comment by ai** [comment]
You should use `postcss-easy-import` (extra features) instead of `postcss-import` (W3C spec polyfill). I will update docs later.

**Comment by ai** [comment]
Done fad24d2

**Comment by DavidOliver** [comment]
Thanks! While that's useful to know, I don't think it covers what I was trying to do:

    @import 'normalize.css' /* plain CSS is inlined as is */

    body
        background-color: pink

    @import 'modules/some-module.sss' /* SugarSS is inlined (and eventually converted to plain CSS) */

However, I've split vendor (plain) CSS into a separate file now, which simplifies things so I no longer need to import plain CSS into a sss file.

**Comment by jmeas** [comment]
This issue should be reopened. It's pretty common to use vendor CSS files, and SugarSS isn't capable of handling that.

One of the nice things about Stylus is that it can parse regular CSS, and its SugarSS-like syntax. I think it'd be pretty rad if SugarSS was a bit more flexible in that regard.

Atm I'm going through my vendor files and updating them to use the SugarSS syntax, which isn't very maintainable.

**Comment by DavidOliver** [comment]
@jmeas,

> Atm I'm going through my vendor files and updating them to use the SugarSS syntax, which isn't very maintainable.

Might it be easier to use a task runner to concatenate the vendor CSS and the CSS results of your SugarSS if you want it all in one CSS file?
