### ISSUE TITLE
Nesting Support

### ISSUE THREAD

**Issue by AlecRust** [postcss/sugarss#34]
Wondering if there's any plans for nesting?

Instead of:
```css
.header
  color: #fff

@media (--md-viewport-min)
  .header
    color: #000
```

We could have:
```css
.header
  color: #fff

  @media (--md-viewport-min)
    color: #000
```

**Comment by ai** [comment]
SugarSS is just a syntax without transformation

Use postcss-nested plugin as you do with CSS syntax 😊

**Comment by AlecRust** [comment]
My apologies, thought I already had that included. Fantastic 👍
