### ISSUE TITLE
Support for postcss-sorting

### ISSUE THREAD

**Issue by RedHatter** [postcss/sugarss#35]
When I run the postcss-sorting atom plugin on this code

```
.screenIn
	position: absolute
	top: 0
	left: 0
	width: 100%
	height: 100%
	z-index: 1
	background-color: #ffffff
	animation: 0.5s fadeIn both
```
I get  `<css input>:3:7: Missed semicolon`

**Comment by 1j01** [comment]
You should probably open an issue on [atom-postcss-sorting](https://github.com/lysyi3m/atom-postcss-sorting).
SugarSS is supposed to work with postcss-sorting, it's even [one of the examples](https://github.com/postcss/sugarss#sugarss-to-sugarss)

**Comment by ai** [comment]
Yeap, sorry, but it is `atom-postcss-sorting` issue. SugarSS could work with any PostCSS plugin.
