### ISSUE TITLE
What is correct way to use @apply ?

### ISSUE THREAD

**Issue by kbytin** [postcss/sugarss#38]
I'm using cssnext and sugarSS 

Cssnext includes  postcss-apply  (https://github.com/pascalduez/postcss-apply)

What is correct way to use it?

```
:root
  --centered: 
      display: flex;
      align-items: center;
      justify-content: center;
```
I get error
`Module build failed: Error: Expected pseudo-class or pseudo-element`
If I use like this
```
:root
  --centered: {
      display: flex;
      align-items: center;
      justify-content: center; }
```
No errors but It doesn't work

**Comment by ai** [comment]
Seems like current logic is not ready for apply. I will have Internet to fix it only after July 8. Is it OK?

**Comment by ai** [comment]
Hm. I tested your example and everything works fine.

Could you:

1. Remove `;` from your example.
2. Post full stack trace of error if it will not be fixed by removing `;`
