### ISSUE TITLE
Best way to load plain CSS

### ISSUE THREAD

**Issue by AlecRust** [postcss/sugarss#39]
What's the best way to load plain CSS files through SugarSS?

For example it would be nice to be able to load Normalize.css from `/node_modules` in the main stylesheet like so using `postcss-import`:

```css
@import "normalize.css"
@import "base/base.sss"
@import "components/button.sss"
etc.
```

The full CSS doesn't play nice when pulled in amongst SugarSS styles though, so I'm currently using [postcss-normalize](https://github.com/seaneking/postcss-normalize) in my plugins to work around this.

Can SugarSS support plain CSS syntax or is there a recommended way to solve this?

**Comment by 1j01** [comment]
See https://github.com/postcss/sugarss/issues/33 (not really resolved)

**Comment by AlecRust** [comment]
Thanks @1j01. Using [postcss-easy-import](https://github.com/TrySound/postcss-easy-import) allows something like Normalize.css to be referenced, but unfortunately the brackets/semi-colons are duplicated when parsed with SugarSS syntax:

![screenshot](https://i.imgur.com/DXGteCP.png)

**Comment by ai** [comment]
Ask postcss-easy-import guys, because all import happen after parsing
