### ISSUE TITLE
postcss-import working?

### ISSUE THREAD

**Issue by FezVrasta** [postcss/sugarss#45]
I tried `postcss-import` with SugarSS and it seems to work just fine. What's up?

**Comment by ai** [comment]
`postcss-import` is W3C spec polyfill, so it will not compile SugarSS. You need to take https://github.com/TrySound/postcss-easy-import

**Comment by ai** [comment]
@TrySound maybe you could help and add `postcss-easy-import` example to SugarSS docs? :)

**Comment by FezVrasta** [comment]
No the concern is that `postcss-import` **actually works**.

**Comment by ai** [comment]
¯\_(ツ)_/¯

**Comment by FezVrasta** [comment]
Care to elaborate? 😅

**Comment by FezVrasta** [comment]
I tried importing a file like this:

```sass
// some comments
// here and there
$var1: red
$var2: white
```

And it compiled just fine.
