### ISSUE TITLE
sss is not defined

### ISSUE THREAD

**Issue by TryHardNinja** [postcss/sugarss#52]
I can not understand what the problem is, I do everything through guide

```
import gulp from 'gulp';
import plumber from 'gulp-plumber';
import gulpIf from 'gulp-if';
var postcss = require('postcss');
var easyImport = require('postcss-easy-import');
var sugarss = require('sugarss');
import gcmq from 'gulp-group-css-media-queries';
import nano from 'gulp-cssnano';
import rename from 'gulp-rename';
import sourcemaps from 'gulp-sourcemaps';
import errorHandler from 'gulp-plumber-error-handler';
```

![screen shot 2016-10-20 at 13 32 04](https://cloud.githubusercontent.com/assets/22329784/19548729/6d20aaf6-96ca-11e6-8f57-89ceec88eab5.png)

**Comment by ai** [comment]
`.process()` example in docs is a example for ugins SugarSS with PostCSS JS API.

You don’t use PostCSS JS API. You use Gulp PostCSS plugin.

**Comment by ai** [comment]
Here is a example for Gulp: https://github.com/postcss/sugarss#sugarss-to-css
