### ISSUE TITLE
transition: opacity

### ISSUE THREAD

**Issue by alexeyMohnatkin** [postcss/sugarss#53]
When I'm trying to set transition: opacity I get error: 

> Module build failed: TypeError: Cannot read property 'input' of null.

 The same with transition-property: opacity

**Comment by ai** [comment]
Give me full error stack trace, PostCSS plugins list and how you run SugarSS/PostCSS.

I think it is not related with SugarSS. But maybe we see a Autoprefixer issue here. Or it is Autoprefixer/SugarSS conflict.

**Comment by alexeyMohnatkin** [comment]
> Error in ./src/css/app.sss
Module build failed: TypeError: Cannot read property 'input' of null
 @ ./src/css/app.sss 4:14-137 13:2-17:4 14:20-143

The problem appears when I include postcss-colour-functions in postcss plugins

**Comment by ai** [comment]
Could you create small test project?

**Comment by alexeyMohnatkin** [comment]
https://github.com/alexeyMohnatkin/sss-opacity-issue

**Comment by ai** [comment]
The problem was in `postcss-colour-functions`. I sent a PR: https://github.com/BHouwens/postcss-colour-functions/pull/2

**Comment by alexeyMohnatkin** [comment]
Thank you!
