### ISSUE TITLE
Ignored line with a comment

### ISSUE THREAD

**Issue by do7be** [postcss/sugarss#54]
I found a bug. When building with a comment it seems to ignore the line, without an error.

```sass
> a // b
  font-size: normal
```

**Comment by Kovensky** [comment]
This snippet seems to reproduce the problem:

```sass
body
  > a // comment
    align-self: center
```

However, this _only_ happens in combination with `cssnano`. When `cssnano` runs, it reduces the `body > a` selector to (an invalid) `>a`; but if the comment is moved to the next line, it correctly reduces to `body>a`.

Something seems to be generating a not exactly correct AST?

**Comment by ai** [comment]
```sass
body
  > a // comment
    font-size: normal
```

compiles to correct:

```css
body {
  > a /* comment */ {
    font-size: normal
  }
}
```

maybe we have a cssnano issue here? @ben-eb

**Comment by ai** [comment]
While we are thinking about issue here is a hot fix (by deleting all comments):

```js
const postcss = require('postcss')
module.exports = postcss.plugin('no-comments', () => {
  return root => {
    root.walkComments(i => i.remove())
  }
})
```

Use this plugin before cssnano

**Comment by Kovensky** [comment]
Interestingly, the same-line comment is not preserved in my output, even without cssnano.

**Comment by ai** [comment]
@ben-eb AST for `> a // comment` looks correct too:

```
Rule {
  raws: 
   { before: '\n  ',
     selector: 
      { value: '> a ',
        raw: '> a /* comment */',
        sss: '> a // comment' } },
  type: 'rule',
  …
```

**Comment by ai** [comment]
@do7be I tested your source and everything was find in SugarSS. This input source:

```sass
> a // b
  font-size: normal
```

compiles to:

```css
> a /* b */ {
  font-size: normal
}
```

**Comment by ben-eb** [comment]
@ai It's not valid CSS; a child combinator should separate two compound selectors. I think this is more of a Sass construct, which cssnano doesn't support.

https://drafts.csswg.org/selectors-4/#child-combinators
