### ISSUE TITLE
Convert SSS to SCSS

### ISSUE THREAD

**Issue by sc0rp10** [postcss/sugarss#58]
Hi.
I have a legacy project with Stylus. I don't want to use it anymore and want to convert the project to SCSS-like syntax (postcss-nested). Is there any option for converting sss to scss with postcss?
I can fix some incompatibles (like mixins calls etc), but I cannot restore braces manually.

**Comment by ai** [comment]
You can set SugarSS as parser and `postcss-scss` as stringifier. But it will be dangerous.

**Comment by sc0rp10** [comment]
Hey, @ai!
Thank you for the advice and for PostCSS, with your help I wrote a small script for stylus -> postcss-scss converting and placed it here: https://github.com/sc0rp10/stylus-to-postcss
