### ISSUE TITLE
Error on SASS syntax variable interpolation

### ISSUE THREAD

**Issue by gespinha** [postcss/sugarss#60]
Hi there,

I'm using Sugarss as a postcss plugin to work with SASS syntax. Using the following example returns and error "Unnecessary curly bracket" because of the `.#{nth($color, $i)}` variable interpolation:

```
$color: red, green, blue
@for $i from 1 through length($color)
  .#{nth($color, $i)}
    color: nth($color, $i)
```

There is no other way, that I know of, to interpolate a variable inside a loop in SASS syntax. Can you please help me understand what is going wrong? Is this a known issue?

Cheers!

**Comment by gespinha** [comment]
Just discovered that wrapping the variable interpolation in quotes will solve the issue. So this will pass:

```
$color: red, green, blue
@for $i from 1 through length($color)
  ."#{nth($color, $i)}"
    color: nth($color, $i)
```

This should be supported without converting it to a string though.

**Comment by ai** [comment]
SugarSS is not Sass. You need postcss-sass.
