### ISSUE TITLE
Webstorm support? (VueJS styles)

### ISSUE THREAD

**Issue by core01** [postcss/sugarss#64]
Hello, is there any plugin for WebStorm?
In my case I want to use sugarss with Vue and style lang="ss" doesn't recognize SugarSS syntax.

![image](https://user-images.githubusercontent.com/2903772/45091675-05978800-b135-11e8-822b-1b140343c66b.png)

I created issue here because you better knows about SugarSS support in WebStorm.
Thank you!

**Comment by ai** [comment]
Hi. Sorry, have no idea about it. You can try to ask for SugarSS support here 

https://plugins.jetbrains.com/plugin/8578-postcss-support

**Comment by core01** [comment]
@ai Thank you for reply, there is no SugarSS support in WebStorm in current versions.
