### ISSUE TITLE
Import Error While Compiling

### ISSUE THREAD

**Issue by Mr-Manna** [postcss/sugarss#65]
I've a **sss** folder with **style.sss**,**_base.sss** & **_footer.sss**

I've postcss.config.js  including >    **'postcss-easy-import':{extensions: ['.sss'] }** & **parser: 'sugarss'**

I've imported : **@import "base"** & ** @import "footer"** in my **style.sss**

Now this is throwing error in console while compiling but actually working in browser correctly and if I put **@import "_base" ** the console error is gone but not working in browser.

> (1:1) Cannot find module 'base' from 'E:\Programing Practice\webpack\src\sss'
>  @ ./src/sss/style.sss 2:14-124
>  @ ./src/index.js
>  @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/index.js

Now should I worry about this!!

**Comment by ai** [comment]
Hi. Unfortunately, this issue should be reported to [postcss-easy-import](https://github.com/TrySound/postcss-easy-import).

I want to help, but all importing stuff happens there and I have no idea how it works inside and what it does.
