### ISSUE TITLE
Fail to support some plugins

### ISSUE THREAD

**Issue by dtvn** [postcss/sugarss#71]
> It was designed to be used with PreCSS and postcss-nested-props

I've tested and it only works with `PreCSS`. But, `postcss-nested-props` and `postcss-easy-import` aren't. Here is how my config:

**.postcssrc.js** - config file for Gulp:
```Js
const fn = require('./style/asset/fn/index.js') // BUG glob doesn't work
const uniVar = require('./style/asset/uniVar.js')


module.exports = {
	parser: 'sugarss',
	plugins: {
		'postcss-advanced-variables': {
			variables: uniVar,
			disable: '@import'
		},
		'postcss-nested': null,
		'postcss-nested-props': null, // BUG 
		'postcss-easy-import': {
			extensions: '.sss' // BUG 
		},
		'postcss-functions': {
			functions: fn
		},
		'cssnano': {
			preset: [
				'default',
				{ discardComments: { removeAll: true } }
			]
		}
	}
}
```

Case **A.sss** - no nested-props:
```sugarss
body
	font:
		size: 12px // It said missing semicolons
```

Output:
![Screenshot from 2019-10-14 15-00-29](https://user-images.githubusercontent.com/43217335/66736557-b2dde300-ee93-11e9-9816-22686d065623.png)

Case **B.sss - no import:
```sugarss
body
	@import 'xyz' // various output
```
1. If I disable `@import` of `postcss-advanced-variables`. PostCSS will copy the whole `@import 'yy'` to the final file.
2. If I enable `@import` of `postcss-advanced-variables`. It will print this message:
> Could not resolve the @import for "layout/thread"

Output:
![](https://user-images.githubusercontent.com/43217335/66736616-e28ceb00-ee93-11e9-9ef2-c14ff8b4fee2.png)
![Screenshot from 2019-10-14 15-10-52](https://user-images.githubusercontent.com/43217335/66736954-d9e8e480-ee94-11e9-9a91-4dfe26f37e5f.png)
I don't think I could find anything in call stack

**Comment by ai** [comment]
Can you show full PostCSS output? The error message with stack trace.

**Comment by dtvn** [comment]
Sure, let me add detail.

**Comment by dtvn** [comment]
I think the problem is the plugins' order. 

If I put it in this order

	'postcss-easy-import': easyIm,
	'postcss-mixins': { mixinsFiles: path.join(rootPath, 'mixins', '*.mjs') },
	'postcss-functions': { glob: path.join(rootPath, 'funcs', '*.mjs') },
	'postcss-nested-props': null,
	'postcss-nested': null

It will work fine. (I forgot where I read this note, the plugins of postcss are read in an up to down order. So this is my bad)
