### ISSUE TITLE
Possible outdated information in the docs

### ISSUE THREAD

**Issue by vitalybaev** [postcss/sugarss#97]
In readme, I've found the following paragraph:

> [postcss-import](https://github.com/postcss/postcss-import) doesn’t support .sss file extension, because this plugin implements W3C specification. If you want smarter @import, you should use [postcss-easy-import](https://github.com/TrySound/postcss-easy-import) with the extensions option.

But it seems that `postcss-import` [supports](https://github.com/postcss/postcss-import/blob/master/lib/process-content.js#L21-L30) SugarSS normally, doesn't it?

**Comment by ai** [comment]
Sorry, I do not use `postcss-import`. Can you make a research?

**Comment by vitalybaev** [comment]
I left the link to the sources, where you can see handling `.sss` files. Here is the link again:

https://github.com/postcss/postcss-import/blob/master/lib/process-content.js#L21-L30

I also noticed that imports work with `postcss-import` when I was implementing SugarSS support in Vite.

**Comment by ai** [comment]
Let’s remove the note if it is not actual anymore. Did you try `sugarss` and `postcss-import` in practice?

If yes, send PR with comment removing.

**Comment by vitalybaev** [comment]
Yes, I tried this with tests in Vite project

https://github.com/vitejs/vite/pull/6705/files#diff-049fcac4d2cafccb313577d936c10b30ccc7f54ac3d3c3043114f068ad7133b2

So, it works correctly with `.sss` files as well. I'll send a PR with fix later
